export type WalletAcademySection = {
  id: string;
  titleEn: string;
  titleNl: string;
  summaryEn: string;
  summaryNl: string;
  pointsEn: string[];
  pointsNl: string[];
  practiceEn: string;
  practiceNl: string;
  warningEn?: string;
  warningNl?: string;
};

export type WalletAcademyTrack = {
  id: string;
  name: string;
  categoryEn: string;
  categoryNl: string;
  platforms: string;
  bestForEn: string;
  bestForNl: string;
  notIdealForEn: string;
  notIdealForNl: string;
  sourceLabel: string;
  sourceUrl: string;
  verifiedOn: string;
  strengthsEn: string[];
  strengthsNl: string[];
  limitationsEn: string[];
  limitationsNl: string[];
  sections: WalletAcademySection[];
};

const VERIFIED_ON = "2026-07-23";

export const WALLET_ACADEMY_TRACKS: WalletAcademyTrack[] = [
  {
    id: "xaman",
    name: "Xaman",
    categoryEn: "XRPL-first mobile self-custody wallet",
    categoryNl: "XRPL-first mobiele self-custodywallet",
    platforms: "iOS · Android",
    bestForEn: "Daily XRPL use, xApps, trustlines, issued assets, NFTs and reviewed sign requests.",
    bestForNl: "Dagelijks XRPL-gebruik, xApps, trustlines, issued assets, NFT’s en gecontroleerde ondertekenverzoeken.",
    notIdealForEn: "Users who only want offline hardware confirmation or who do not want to manage recovery material themselves.",
    notIdealForNl: "Gebruikers die uitsluitend offline hardwarebevestiging willen of geen herstelgegevens zelf willen beheren.",
    sourceLabel: "Xaman Help Center",
    sourceUrl: "https://help.xaman.app/app/getting-started-with-xaman",
    verifiedOn: VERIFIED_ON,
    strengthsEn: [
      "Purpose-built around the XRP Ledger and Xahau ecosystems.",
      "Clear sign-request flow through QR codes, deep links and xApps.",
      "Supports full-access and read-only account use cases.",
      "Broad XRPL education and account-management documentation.",
    ],
    strengthsNl: [
      "Specifiek gebouwd rond de XRP Ledger- en Xahau-ecosystemen.",
      "Duidelijke sign-requestflow via QR-codes, deeplinks en xApps.",
      "Ondersteunt full-access- en read-onlyaccounts.",
      "Uitgebreide documentatie voor XRPL-gebruik en accountbeheer.",
    ],
    limitationsEn: [
      "A phone is part of the signing environment, so device security matters.",
      "xApps are third-party applications and must be reviewed individually.",
      "Self-custody means lost recovery material can mean permanent loss of access.",
      "A successful screen is not enough; the ledger transaction still needs verification.",
    ],
    limitationsNl: [
      "De telefoon maakt deel uit van de ondertekenomgeving; toestelbeveiliging is dus belangrijk.",
      "xApps zijn externe applicaties en moeten afzonderlijk worden gecontroleerd.",
      "Bij self-custody kan verlies van herstelgegevens permanent toegangsverlies betekenen.",
      "Een groen scherm is niet genoeg; de ledgertransactie moet nog worden geverifieerd.",
    ],
    sections: [
      {
        id: "model",
        titleEn: "How Xaman controls an XRPL account",
        titleNl: "Hoe Xaman een XRPL-account beheert",
        summaryEn: "Xaman is an interface for XRPL accounts. The assets remain recorded on-ledger; the wallet protects the signing authority used to approve transactions.",
        summaryNl: "Xaman is een interface voor XRPL-accounts. De assets blijven on-ledger geregistreerd; de wallet beschermt de ondertekenbevoegdheid waarmee transacties worden goedgekeurd.",
        pointsEn: [
          "An r-address is public and can be viewed without signing access.",
          "Full-access accounts can sign; read-only accounts can inspect without spending authority.",
          "The wallet cannot reverse a validated XRPL transaction.",
          "Account reserves, trustlines and account settings live on the ledger, not inside the app.",
        ],
        pointsNl: [
          "Een r-adres is openbaar en kan zonder ondertekenrechten worden bekeken.",
          "Full-accessaccounts kunnen tekenen; read-onlyaccounts kunnen alleen inspecteren.",
          "De wallet kan een gevalideerde XRPL-transactie niet terugdraaien.",
          "Accountreserves, trustlines en instellingen staan op de ledger, niet in de app.",
        ],
        practiceEn: "Open an XRPL explorer and compare the public account data with what Xaman displays. Do not sign anything.",
        practiceNl: "Open een XRPL-explorer en vergelijk de openbare accountdata met wat Xaman toont. Onderteken niets.",
      },
      {
        id: "setup",
        titleEn: "Installation and first account",
        titleNl: "Installatie en eerste account",
        summaryEn: "Install only from the official store listing, create or import the intended account type and confirm that recovery material is recorded offline before funding the account.",
        summaryNl: "Installeer uitsluitend via de officiële storevermelding, maak of importeer het bedoelde accounttype en leg herstelgegevens offline vast voordat je het account financiert.",
        pointsEn: [
          "Verify publisher, app name and official help links before installation.",
          "Choose between creating a new account, importing an existing account or using read-only mode.",
          "Test account access before transferring a meaningful balance.",
          "Keep the app passcode and the account signing credentials conceptually separate.",
        ],
        pointsNl: [
          "Controleer uitgever, appnaam en officiële helplinks vóór installatie.",
          "Kies bewust tussen een nieuw account, import van een bestaand account of read-onlymodus.",
          "Test de accounttoegang voordat je een betekenisvol saldo verstuurt.",
          "Houd de app-pincode en accountondertekengegevens conceptueel gescheiden.",
        ],
        practiceEn: "Create a read-only account for a public address and identify which actions are deliberately unavailable.",
        practiceNl: "Maak een read-onlyaccount voor een openbaar adres en benoem welke handelingen bewust niet beschikbaar zijn.",
        warningEn: "Never enter recovery secrets into a website, chat, support form or xApp.",
        warningNl: "Voer herstelgeheimen nooit in op een website, in een chat, supportformulier of xApp.",
      },
      {
        id: "signing",
        titleEn: "Reviewing sign requests",
        titleNl: "Ondertekenverzoeken controleren",
        summaryEn: "A Xaman payload is a transaction template presented for approval. The user must review the transaction type and all meaningful fields before signing.",
        summaryNl: "Een Xaman-payload is een transactiesjabloon dat ter goedkeuring wordt aangeboden. De gebruiker moet transactietype en alle betekenisvolle velden controleren vóór ondertekening.",
        pointsEn: [
          "Confirm the selected account and network.",
          "Check transaction type, destination, delivered asset, amount, issuer, tags and memos.",
          "Reject unclear, unexpected or time-pressured requests.",
          "After signing, verify the final hash and validated result independently.",
        ],
        pointsNl: [
          "Controleer het geselecteerde account en netwerk.",
          "Controleer transactietype, bestemming, asset, bedrag, issuer, tags en memo’s.",
          "Weiger onduidelijke, onverwachte of onder tijdsdruk aangeboden verzoeken.",
          "Controleer na ondertekening onafhankelijk de definitieve hash en validatie.",
        ],
        practiceEn: "Open a harmless sign request, identify every displayed transaction field and reject it instead of signing.",
        practiceNl: "Open een onschuldig ondertekenverzoek, benoem ieder zichtbaar transactieveld en wijs het verzoek af in plaats van te tekenen.",
      },
      {
        id: "xrpl-features",
        titleEn: "Trustlines, issued assets, DEX, AMM and NFTs",
        titleNl: "Trustlines, issued assets, DEX, AMM en NFT’s",
        summaryEn: "Xaman exposes XRPL functionality directly or through xApps. Every feature changes ledger state and can affect reserves, exposure and recovery options.",
        summaryNl: "Xaman ontsluit XRPL-functionaliteit direct of via xApps. Iedere functie wijzigt ledgerstatus en kan reserves, blootstelling en herstelmogelijkheden beïnvloeden.",
        pointsEn: [
          "A trustline authorizes holding a specific issued currency from a specific issuer.",
          "DEX and AMM actions require review of issuer, price, spread, slippage and available liquidity.",
          "NFT offers can transfer ownership; inspect NFTokenID, amount and destination.",
          "Account settings such as regular keys, master-key disabling and multisigning require advanced recovery planning.",
        ],
        pointsNl: [
          "Een trustline staat toe dat je een specifieke issued currency van een specifieke issuer houdt.",
          "DEX- en AMM-acties vereisen controle van issuer, prijs, spread, slippage en liquiditeit.",
          "NFT-offers kunnen eigendom overdragen; controleer NFTokenID, bedrag en bestemming.",
          "Regular keys, uitschakelen van de master key en multisigning vereisen geavanceerde herstelplanning.",
        ],
        practiceEn: "On TESTNET, create one trustline, inspect the resulting TrustSet transaction and explain the new reserve impact.",
        practiceNl: "Maak op TESTNET één trustline, inspecteer de TrustSet-transactie en leg de nieuwe reserve-impact uit.",
      },
      {
        id: "recovery",
        titleEn: "Recovery, migration and device loss",
        titleNl: "Herstel, migratie en toestelverlies",
        summaryEn: "Recovery must be planned before loss. Know whether the account uses secret numbers, a family seed, mnemonic material, a hardware signer, regular key or multisign configuration.",
        summaryNl: "Herstel moet vóór verlies zijn gepland. Weet of het account secret numbers, een family seed, mnemonic, hardware signer, regular key of multisignconfiguratie gebruikt.",
        pointsEn: [
          "Document the account type without copying the secret into cloud notes.",
          "Test recovery with a low-value account before relying on the process.",
          "Keep offline backups physically separated.",
          "If the signing model uses a hardware card or external key, document that dependency.",
        ],
        pointsNl: [
          "Documenteer het accounttype zonder het geheim naar cloudnotities te kopiëren.",
          "Test herstel met een account van lage waarde voordat je erop vertrouwt.",
          "Bewaar offlineback-ups fysiek gescheiden.",
          "Documenteer afhankelijkheden van hardwarekaarten of externe sleutels.",
        ],
        practiceEn: "Write a recovery checklist that another trusted person could follow without revealing the secret itself.",
        practiceNl: "Schrijf een herstelchecklist die een vertrouwd persoon kan volgen zonder het geheim zelf te onthullen.",
      },
      {
        id: "decision",
        titleEn: "When Xaman is or is not the right choice",
        titleNl: "Wanneer Xaman wel of niet passend is",
        summaryEn: "Xaman is strong for active XRPL participation. Larger treasury balances may require hardware isolation, multisigning or operational separation.",
        summaryNl: "Xaman is sterk voor actieve XRPL-participatie. Grotere treasurybalansen kunnen hardware-isolatie, multisigning of functiescheiding vereisen.",
        pointsEn: [
          "Good fit: active XRPL learner, xApp user, token/NFT participant or mobile signer.",
          "Consider separation: one daily-use wallet and one long-term or treasury account.",
          "Avoid concentrating every operational role in one phone and one account.",
          "Choose the security model based on consequence of loss, not convenience alone.",
        ],
        pointsNl: [
          "Goede match: actieve XRPL-leerling, xApp-gebruiker, token/NFT-deelnemer of mobiele ondertekenaar.",
          "Overweeg scheiding: één dagelijkse wallet en één langetermijn- of treasuryaccount.",
          "Concentreer niet iedere operationele rol in één telefoon en één account.",
          "Kies het beveiligingsmodel op basis van de gevolgen van verlies, niet alleen gemak.",
        ],
        practiceEn: "Design a two-wallet model for daily use and long-term storage and explain which transactions belong in each.",
        practiceNl: "Ontwerp een tweewalletmodel voor dagelijks gebruik en langetermijnopslag en leg uit welke transacties waar thuishoren.",
      },
    ],
  },
  {
    id: "tangem",
    name: "Tangem",
    categoryEn: "NFC hardware wallet with mobile interface",
    categoryNl: "NFC-hardwarewallet met mobiele interface",
    platforms: "Tangem card/ring · iOS · Android",
    bestForEn: "Users who want hardware-isolated keys with a simple NFC mobile workflow.",
    bestForNl: "Gebruikers die hardwaregeïsoleerde sleutels willen met een eenvoudige mobiele NFC-flow.",
    notIdealForEn: "Users who require an on-device screen, broad XRPL-native dApp support or workflows without an NFC phone.",
    notIdealForNl: "Gebruikers die een scherm op het apparaat, brede XRPL-native dApp-ondersteuning of gebruik zonder NFC-telefoon nodig hebben.",
    sourceLabel: "Tangem XRP and Help Center",
    sourceUrl: "https://tangem.com/en/help-center/introduction-to-tangem-wallet/tangem-wallet-overview/",
    verifiedOn: VERIFIED_ON,
    strengthsEn: [
      "Private keys are generated and stored in the hardware secure element.",
      "Card or ring communicates with the mobile app through NFC.",
      "Multi-card backup options can reduce single-device risk.",
      "Supports XRP Ledger XRP and selected XRPL issued assets.",
    ],
    strengthsNl: [
      "Privésleutels worden in het beveiligde hardware-element gegenereerd en opgeslagen.",
      "Kaart of ring communiceert via NFC met de mobiele app.",
      "Meerdere back-upkaarten kunnen single-device-risico verminderen.",
      "Ondersteunt XRP op de XRP Ledger en geselecteerde XRPL-issued assets.",
    ],
    limitationsEn: [
      "The card has no display, so transaction details are reviewed on the phone.",
      "A compatible NFC phone and functioning app are operational dependencies.",
      "XRPL feature coverage can differ from an XRPL-first wallet.",
      "Current app limitations, including trustline management, must be checked before use.",
    ],
    limitationsNl: [
      "De kaart heeft geen scherm; transactiedetails worden op de telefoon gecontroleerd.",
      "Een compatibele NFC-telefoon en werkende app zijn operationele afhankelijkheden.",
      "XRPL-functionaliteit kan beperkter zijn dan bij een XRPL-first wallet.",
      "Controleer actuele appbeperkingen, waaronder trustlinebeheer, vóór gebruik.",
    ],
    sections: [
      {
        id: "model",
        titleEn: "Card, secure element and mobile app",
        titleNl: "Kaart, secure element en mobiele app",
        summaryEn: "The physical Tangem device stores the private key. The mobile app prepares and displays transactions, while NFC communication asks the card to authorize them.",
        summaryNl: "Het fysieke Tangem-apparaat bewaart de privésleutel. De mobiele app stelt transacties samen en toont ze; via NFC wordt de kaart om goedkeuring gevraagd.",
        pointsEn: [
          "The card or ring has no battery, screen or internet connection.",
          "The mobile app is the user interface, not the sole key store in the hardware setup.",
          "The security model depends on both hardware possession and access controls.",
          "Review the phone screen carefully because the card itself cannot display the destination.",
        ],
        pointsNl: [
          "De kaart of ring heeft geen batterij, scherm of internetverbinding.",
          "De mobiele app is de interface, niet de enige sleutelopslag in de hardwareopstelling.",
          "Het beveiligingsmodel hangt af van hardwarebezit en toegangsbeveiliging.",
          "Controleer het telefoonscherm zorgvuldig omdat de kaart zelf geen bestemming toont.",
        ],
        practiceEn: "Describe which parts of a Tangem transaction happen on the phone and which part requires the card.",
        practiceNl: "Beschrijf welke onderdelen van een Tangem-transactie op de telefoon gebeuren en welk onderdeel de kaart vereist.",
      },
      {
        id: "setup",
        titleEn: "Activation and backup choices",
        titleNl: "Activering en back-upkeuzes",
        summaryEn: "During activation, choose the intended backup model before transferring funds. A seedless multi-card model and a seed-phrase model have different recovery assumptions.",
        summaryNl: "Kies tijdens activering het bedoelde back-upmodel vóór je vermogen overmaakt. Een seedless multikaartmodel en seed-phrasemodel hebben verschillende herstelaannames.",
        pointsEn: [
          "Buy only through a trusted sales route and inspect packaging and cards.",
          "Create all intended backup cards during the controlled setup session.",
          "Set access codes and biometrics without reusing weak credentials.",
          "Test every backup card before meaningful funding.",
        ],
        pointsNl: [
          "Koop uitsluitend via een betrouwbare verkooproute en inspecteer verpakking en kaarten.",
          "Maak alle bedoelde back-upkaarten tijdens de gecontroleerde setup aan.",
          "Stel toegangscodes en biometrie in zonder zwakke hergebruikte gegevens.",
          "Test iedere back-upkaart vóór betekenisvolle financiering.",
        ],
        practiceEn: "Create a written inventory of cards, storage locations and the recovery model without recording access codes in the same document.",
        practiceNl: "Maak een inventaris van kaarten, opslaglocaties en herstelmodel zonder toegangscodes in hetzelfde document te zetten.",
      },
      {
        id: "xrpl",
        titleEn: "Using XRP and XRPL issued assets",
        titleNl: "XRP en XRPL-issued assets gebruiken",
        summaryEn: "Tangem supports XRP Ledger XRP and can add XRPL tokens through trustlines. Feature support should be checked in the current app before relying on advanced account operations.",
        summaryNl: "Tangem ondersteunt XRP op de XRP Ledger en kan XRPL-tokens via trustlines toevoegen. Controleer actuele appondersteuning voordat je op geavanceerde accountfuncties vertrouwt.",
        pointsEn: [
          "Confirm that the selected XRP asset uses the XRP Ledger network.",
          "A trustline is specific to currency and issuer; verify both before opening it.",
          "Opening a trustline changes account reserve requirements.",
          "Do not assume every XRPL feature available on-ledger is exposed in the Tangem interface.",
        ],
        pointsNl: [
          "Controleer dat de gekozen XRP-asset het XRP Ledger-netwerk gebruikt.",
          "Een trustline is specifiek voor currency en issuer; controleer beide.",
          "Een trustline wijzigt de accountreservevereisten.",
          "Neem niet aan dat iedere on-ledger XRPL-functie in Tangem beschikbaar is.",
        ],
        practiceEn: "Before adding a token, write down the currency code, issuer address, official source and reason for opening the trustline.",
        practiceNl: "Noteer vóór het toevoegen van een token de currencycode, issuerwallet, officiële bron en reden voor de trustline.",
        warningEn: "The Tangem help center currently states that closing an XRPL trustline in the app is not available; verify this again before use.",
        warningNl: "Het Tangem-helpcentrum vermeldt momenteel dat een XRPL-trustline niet in de app kan worden gesloten; controleer dit opnieuw vóór gebruik.",
      },
      {
        id: "signing",
        titleEn: "Transaction review without a hardware screen",
        titleNl: "Transactiecontrole zonder hardwarescherm",
        summaryEn: "Because the card has no display, the user must treat the phone as the transaction-display environment while the card supplies hardware authorization.",
        summaryNl: "Omdat de kaart geen scherm heeft, is de telefoon de omgeving voor transactiedetails terwijl de kaart hardwarematige goedkeuring levert.",
        pointsEn: [
          "Verify app authenticity and phone integrity.",
          "Review destination, network, asset, issuer and amount before tapping the card.",
          "Use a separate explorer to confirm the final validated transaction.",
          "Avoid approving while screen sharing or following instructions from an unknown caller.",
        ],
        pointsNl: [
          "Controleer appauthenticiteit en integriteit van de telefoon.",
          "Controleer bestemming, netwerk, asset, issuer en bedrag vóór het tappen.",
          "Bevestig de gevalideerde transactie via een aparte explorer.",
          "Keur niets goed tijdens schermdelen of instructies van onbekende bellers.",
        ],
        practiceEn: "Simulate a send flow, stop before card confirmation and list every field that must match your intent.",
        practiceNl: "Simuleer een verzendflow, stop vóór kaartbevestiging en noteer ieder veld dat met je bedoeling moet overeenkomen.",
      },
      {
        id: "recovery",
        titleEn: "Loss, damage and backup-card planning",
        titleNl: "Verlies, schade en back-upkaartplanning",
        summaryEn: "The recovery plan depends on the setup chosen. Multiple cards can provide redundancy, but storing all cards together recreates a single point of failure.",
        summaryNl: "Het herstelplan hangt af van de gekozen setup. Meerdere kaarten geven redundantie, maar gezamenlijke opslag maakt opnieuw één uitvalspunt.",
        pointsEn: [
          "Store backup cards in separate controlled locations.",
          "Know whether your configuration includes a recoverable seed phrase.",
          "Test backup access periodically without exposing meaningful funds.",
          "Plan replacement before the last functioning card is lost or damaged.",
        ],
        pointsNl: [
          "Bewaar back-upkaarten op gescheiden gecontroleerde locaties.",
          "Weet of je configuratie een herstelbare seed phrase bevat.",
          "Test back-uptoegang periodiek zonder betekenisvolle fondsen bloot te stellen.",
          "Plan vervanging vóór de laatste werkende kaart verloren of beschadigd raakt.",
        ],
        practiceEn: "Create a failure table for lost phone, lost primary card, lost backup card and loss of all devices.",
        practiceNl: "Maak een faaltabel voor verloren telefoon, primaire kaart, back-upkaart en verlies van alle apparaten.",
      },
      {
        id: "decision",
        titleEn: "When Tangem is or is not the right choice",
        titleNl: "Wanneer Tangem wel of niet passend is",
        summaryEn: "Tangem can simplify cold-key use, but users must accept phone-based transaction display and check whether required XRPL features are supported.",
        summaryNl: "Tangem kan cold-keygebruik vereenvoudigen, maar gebruikers moeten telefoonweergave accepteren en controleren of benodigde XRPL-functies worden ondersteund.",
        pointsEn: [
          "Good fit: mobile hardware isolation with simple NFC use.",
          "Consider alternatives: on-device transaction display or deep XRPL-native functionality.",
          "Use separate operational and long-term accounts when risk justifies it.",
          "Do not select hardware by marketing alone; compare recovery and transaction-verification models.",
        ],
        pointsNl: [
          "Goede match: mobiele hardware-isolatie met eenvoudig NFC-gebruik.",
          "Overweeg alternatieven bij behoefte aan on-deviceweergave of diepe XRPL-functionaliteit.",
          "Gebruik gescheiden operationele en langetermijnaccounts wanneer risico dit rechtvaardigt.",
          "Kies hardware niet alleen op marketing; vergelijk herstel- en verificatiemodellen.",
        ],
        practiceEn: "Compare Tangem and Xaman for one daily-use account and one long-term account. Explain your selection without calling either universally safest.",
        practiceNl: "Vergelijk Tangem en Xaman voor dagelijks gebruik en langetermijnopslag. Leg je keuze uit zonder één wallet universeel het veiligst te noemen.",
      },
    ],
  },
  {
    id: "ledger",
    name: "Ledger",
    categoryEn: "Screen-based hardware wallet",
    categoryNl: "Hardwarewallet met scherm",
    platforms: "Ledger device · Ledger Live · compatible third-party apps",
    bestForEn: "Users who want keys isolated in hardware and transaction confirmation on a physical device screen.",
    bestForNl: "Gebruikers die sleutels in hardware willen isoleren en transacties op een fysiek scherm willen bevestigen.",
    notIdealForEn: "Users who need every XRPL token, DEX, NFT or dApp workflow directly inside one native interface.",
    notIdealForNl: "Gebruikers die iedere XRPL-token-, DEX-, NFT- of dAppflow direct in één native interface nodig hebben.",
    sourceLabel: "Ledger Support",
    sourceUrl: "https://support.ledger.com/article/115005177349-zd",
    verifiedOn: VERIFIED_ON,
    strengthsEn: [
      "Private keys remain inside a dedicated hardware device.",
      "Transaction approval requires physical device interaction.",
      "The device screen can independently display critical transaction details.",
      "Suitable for separating long-term holdings from daily-use wallets.",
    ],
    strengthsNl: [
      "Privésleutels blijven in een speciaal hardwareapparaat.",
      "Transactiegoedkeuring vereist fysieke interactie.",
      "Het apparaatscherm kan kritieke transactiedetails onafhankelijk tonen.",
      "Geschikt voor scheiding van langetermijnbezit en dagelijkse wallets.",
    ],
    limitationsEn: [
      "Ledger Live may not expose every XRPL-native feature.",
      "Advanced XRPL activity can require compatible third-party software.",
      "Firmware, device-app and desktop/mobile software updates create operational dependencies.",
      "A recovery phrase remains a high-value secret and must be protected offline.",
    ],
    limitationsNl: [
      "Ledger Live ontsluit mogelijk niet iedere XRPL-native functie.",
      "Geavanceerd XRPL-gebruik kan compatibele externe software vereisen.",
      "Firmware-, device-app- en software-updates creëren operationele afhankelijkheden.",
      "De recovery phrase blijft een waardevol geheim dat offline moet worden beschermd.",
    ],
    sections: [
      {
        id: "model",
        titleEn: "Hardware signing and screen confirmation",
        titleNl: "Hardwareondertekening en schermbevestiging",
        summaryEn: "The computer or phone prepares a transaction, but the Ledger device holds the signing key and requires physical confirmation.",
        summaryNl: "Computer of telefoon stelt een transactie samen, maar het Ledger-apparaat bewaart de ondertekeningssleutel en vereist fysieke bevestiging.",
        pointsEn: [
          "The host device can request a transaction but should not be trusted blindly.",
          "Review destination, amount and transaction details on the hardware screen.",
          "The XRP app on the device must be installed and available for signing.",
          "The public address can be monitored without connecting the hardware device.",
        ],
        pointsNl: [
          "Het hostapparaat kan een transactie aanvragen maar mag niet blind worden vertrouwd.",
          "Controleer bestemming, bedrag en details op het hardwarescherm.",
          "De XRP-app moet op het apparaat geïnstalleerd en beschikbaar zijn.",
          "Het openbare adres kan zonder aangesloten hardware worden gemonitord.",
        ],
        practiceEn: "Compare the transaction shown by the host application with the details shown on the Ledger device before rejecting the test request.",
        practiceNl: "Vergelijk de transactie in de hostapp met de details op het Ledger-apparaat voordat je het testverzoek afwijst.",
      },
      {
        id: "setup",
        titleEn: "Genuine-device setup and recovery phrase",
        titleNl: "Authentieke setup en recovery phrase",
        summaryEn: "Initialize the device yourself, verify it through official software and record the recovery phrase offline without digital copies.",
        summaryNl: "Initialiseer het apparaat zelf, verifieer het via officiële software en leg de recovery phrase offline vast zonder digitale kopieën.",
        pointsEn: [
          "Never use a device that arrives with a prewritten recovery phrase.",
          "Install Ledger Live only from the official source.",
          "Choose a strong device PIN and keep it separate from the recovery phrase.",
          "Test address generation and a small receive/send cycle before larger transfers.",
        ],
        pointsNl: [
          "Gebruik nooit een apparaat met een vooraf opgeschreven recovery phrase.",
          "Installeer Ledger Live uitsluitend via de officiële bron.",
          "Kies een sterke apparaat-PIN en houd die gescheiden van de recovery phrase.",
          "Test adresgeneratie en een kleine ontvang/verzendcyclus vóór grotere overdrachten.",
        ],
        practiceEn: "Write a setup checklist that identifies which values may be public and which must never leave the offline recovery process.",
        practiceNl: "Schrijf een setupchecklist die onderscheidt welke waarden openbaar mogen zijn en welke nooit het offlineherstelproces mogen verlaten.",
      },
      {
        id: "xrpl",
        titleEn: "XRP accounts and advanced XRPL compatibility",
        titleNl: "XRP-accounts en geavanceerde XRPL-compatibiliteit",
        summaryEn: "Ledger can protect an XRPL signing key, while the available user actions depend on the software connected to the device.",
        summaryNl: "Ledger kan een XRPL-ondertekeningssleutel beschermen; beschikbare handelingen hangen af van de gekoppelde software.",
        pointsEn: [
          "Basic XRP receive and send workflows may be available in Ledger Live.",
          "Issued assets, trustlines, NFTs or DEX actions can require compatible XRPL software.",
          "Verify derivation path and account address when moving between interfaces.",
          "Do not import the hardware recovery phrase into a software wallet merely for convenience.",
        ],
        pointsNl: [
          "Basisontvangst en -verzending van XRP kan via Ledger Live beschikbaar zijn.",
          "Issued assets, trustlines, NFT’s of DEX-acties kunnen externe XRPL-software vereisen.",
          "Controleer derivation path en accountadres bij wisselen tussen interfaces.",
          "Importeer de hardware-recovery phrase niet uit gemak in een softwarewallet.",
        ],
        practiceEn: "Research whether the exact XRPL transaction type you need is supported by the selected interface before connecting the device.",
        practiceNl: "Onderzoek vóór aansluiting of het benodigde XRPL-transactietype door de gekozen interface wordt ondersteund.",
      },
      {
        id: "signing",
        titleEn: "Blind signing and transaction interpretation",
        titleNl: "Blind signing en transactie-interpretatie",
        summaryEn: "Hardware security is weakened when the device cannot show meaningful transaction details and the user approves opaque data.",
        summaryNl: "Hardwarebeveiliging wordt verzwakt wanneer het apparaat geen betekenisvolle details toont en de gebruiker ondoorzichtige data goedkeurt.",
        pointsEn: [
          "Prefer interfaces and transaction types that produce human-readable device confirmation.",
          "Reject requests whose displayed information cannot be matched to the intended action.",
          "Confirm network and account before every session.",
          "Verify the validated transaction hash after approval.",
        ],
        pointsNl: [
          "Geef voorkeur aan interfaces en transactietypen met leesbare apparaatbevestiging.",
          "Weiger verzoeken waarvan de getoonde informatie niet met de bedoeling overeenkomt.",
          "Controleer netwerk en account vóór iedere sessie.",
          "Controleer na goedkeuring de gevalideerde transactiehash.",
        ],
        practiceEn: "Create a rule: no signing when the hardware screen cannot explain destination, amount or transaction intent sufficiently.",
        practiceNl: "Maak een regel: niet tekenen wanneer het hardwarescherm bestemming, bedrag of transactiedoel onvoldoende verklaart.",
      },
      {
        id: "recovery",
        titleEn: "Device replacement and recovery drills",
        titleNl: "Apparaatvervanging en hersteloefeningen",
        summaryEn: "The recovery phrase, not the physical device, is normally the ultimate recovery authority. Protect it against theft, fire, loss and accidental disclosure.",
        summaryNl: "De recovery phrase, niet het fysieke apparaat, is normaal de uiteindelijke herstelbevoegdheid. Bescherm tegen diefstal, brand, verlies en openbaarmaking.",
        pointsEn: [
          "Store recovery material offline in controlled locations.",
          "Never type it into Ledger Live, a browser, email or support chat.",
          "Plan how heirs or trusted representatives can recover without routine access.",
          "Use a low-value recovery drill or spare device to validate the procedure.",
        ],
        pointsNl: [
          "Bewaar herstelgegevens offline op gecontroleerde locaties.",
          "Typ ze nooit in Ledger Live, browser, e-mail of supportchat.",
          "Plan hoe erfgenamen of vertrouwenspersonen kunnen herstellen zonder dagelijkse toegang.",
          "Gebruik een oefenaccount of reserveapparaat om de procedure te valideren.",
        ],
        practiceEn: "Document a replacement-device procedure and the official verification steps before a device is lost.",
        practiceNl: "Documenteer een vervangingsprocedure en officiële verificatiestappen voordat een apparaat verloren raakt.",
      },
      {
        id: "decision",
        titleEn: "When Ledger is or is not the right choice",
        titleNl: "Wanneer Ledger wel of niet passend is",
        summaryEn: "Ledger is often suitable for hardware-isolated signing, but the complete workflow includes host software, firmware, device apps and recovery operations.",
        summaryNl: "Ledger is vaak geschikt voor hardwaregeïsoleerde ondertekening, maar de volledige flow omvat hostsoftware, firmware, apparaatapps en herstelprocessen.",
        pointsEn: [
          "Good fit: long-term holdings, treasury separation or controlled hardware approval.",
          "Consider a second wallet for daily xApp or browser interaction.",
          "Verify required XRPL feature compatibility before choosing it as the only wallet.",
          "Evaluate recovery complexity and operational discipline alongside hardware security.",
        ],
        pointsNl: [
          "Goede match: langetermijnbezit, treasuryscheiding of gecontroleerde hardwaregoedkeuring.",
          "Overweeg een tweede wallet voor dagelijks xApp- of browsergebruik.",
          "Controleer XRPL-featurecompatibiliteit voordat dit de enige wallet wordt.",
          "Beoordeel herstelcomplexiteit en operationele discipline naast hardwarebeveiliging.",
        ],
        practiceEn: "Design a hardware-plus-daily-wallet model and state the maximum role and balance each account should have.",
        practiceNl: "Ontwerp een hardware-plus-dagelijkse-walletmodel en bepaal maximale rol en balans per account.",
      },
    ],
  },
  {
    id: "crossmark",
    name: "Crossmark",
    categoryEn: "XRPL browser-extension wallet",
    categoryNl: "XRPL-browserextensiewallet",
    platforms: "Chrome · Firefox · Brave · compatible browsers",
    bestForEn: "Desktop XRPL dApps, builders, multiple profiles and browser-based signing.",
    bestForNl: "Desktop XRPL-dApps, builders, meerdere profielen en browserondertekening.",
    notIdealForEn: "Users who do not need dApps or who want keys isolated from the browser environment.",
    notIdealForNl: "Gebruikers zonder dApp-behoefte of die sleutels buiten de browseromgeving willen isoleren.",
    sourceLabel: "Crossmark official site and docs",
    sourceUrl: "https://crossmark.io/",
    verifiedOn: VERIFIED_ON,
    strengthsEn: [
      "XRPL-focused browser extension with dApp signing.",
      "Supports multiple profiles and network-oriented cards.",
      "Encrypted private keys remain on the user device according to the provider.",
      "Developer SDK supports sign-in, signing, submission and response handling.",
    ],
    strengthsNl: [
      "XRPL-gerichte browserextensie met dApp-ondertekening.",
      "Ondersteunt meerdere profielen en netwerkgerichte cards.",
      "Versleutelde privésleutels blijven volgens de aanbieder op het gebruikersapparaat.",
      "Developer-SDK ondersteunt login, signing, submission en responseverwerking.",
    ],
    limitationsEn: [
      "Browser extensions share risk with the browser, operating system and installed extensions.",
      "dApp permission and transaction requests can become routine and easy to approve blindly.",
      "Profiles and cards improve organization but do not replace key separation.",
      "The provider website should be rechecked for current audit and network-support claims.",
    ],
    limitationsNl: [
      "Browserextensies delen risico met browser, besturingssysteem en andere extensies.",
      "dApp-verzoeken kunnen routine worden en te gemakkelijk blind worden goedgekeurd.",
      "Profielen en cards verbeteren organisatie maar vervangen geen sleutelscheiding.",
      "Controleer actuele audit- en netwerkclaims opnieuw op de officiële site.",
    ],
    sections: [
      {
        id: "model",
        titleEn: "Extension wallet and dApp connection model",
        titleNl: "Extensiewallet- en dApp-verbindingsmodel",
        summaryEn: "Crossmark injects a wallet interface into supported browser sessions so websites can request sign-in and XRPL transaction approval.",
        summaryNl: "Crossmark voegt een walletinterface toe aan ondersteunde browsersessies zodat websites login en XRPL-transactiegoedkeuring kunnen aanvragen.",
        pointsEn: [
          "The dApp proposes an action; the wallet must present it for user approval.",
          "The extension should never send private keys to the website.",
          "Network and active profile affect which account signs.",
          "A browser connection does not prove a website is trustworthy.",
        ],
        pointsNl: [
          "De dApp stelt een actie voor; de wallet moet die ter goedkeuring tonen.",
          "De extensie mag privésleutels nooit naar de website sturen.",
          "Netwerk en actief profiel bepalen welk account tekent.",
          "Een walletverbinding bewijst niet dat een website betrouwbaar is.",
        ],
        practiceEn: "Connect to a known test dApp, inspect the requested account and network, then disconnect without signing.",
        practiceNl: "Verbind met een bekende test-dApp, controleer account en netwerk en verbreek zonder te tekenen.",
      },
      {
        id: "setup",
        titleEn: "Safe browser and extension setup",
        titleNl: "Veilige browser- en extensiesetup",
        summaryEn: "Install from the official extension listing, use a dedicated browser profile and minimize unrelated extensions on the signing profile.",
        summaryNl: "Installeer via de officiële extensievermelding, gebruik een apart browserprofiel en minimaliseer andere extensies in het signingprofiel.",
        pointsEn: [
          "Verify the extension publisher and official download link.",
          "Create a dedicated browser profile for XRPL activity.",
          "Protect the extension with a strong unique password.",
          "Review browser sync settings before allowing wallet data to synchronize.",
        ],
        pointsNl: [
          "Controleer extensie-uitgever en officiële downloadlink.",
          "Maak een apart browserprofiel voor XRPL-activiteit.",
          "Bescherm de extensie met een sterk uniek wachtwoord.",
          "Controleer browsersynchronisatie voordat walletdata kan synchroniseren.",
        ],
        practiceEn: "List every installed extension in the signing browser profile and remove anything that is not required.",
        practiceNl: "Maak een lijst van alle extensies in het signingprofiel en verwijder alles wat niet nodig is.",
      },
      {
        id: "profiles",
        titleEn: "Profiles, cards and account separation",
        titleNl: "Profielen, cards en accountscheiding",
        summaryEn: "Crossmark offers organizational layers for accounts and networks. Use them to reduce mistakes, while keeping high-risk roles on genuinely separate keys where necessary.",
        summaryNl: "Crossmark biedt organisatielagen voor accounts en netwerken. Gebruik die tegen fouten, maar houd hoogrisicorollen waar nodig op echt gescheiden sleutels.",
        pointsEn: [
          "Label mainnet, testnet and devnet contexts clearly.",
          "Separate personal, builder, treasury and testing roles.",
          "A profile label does not prevent compromise of the underlying device.",
          "Confirm the selected card/profile before every signature.",
        ],
        pointsNl: [
          "Label mainnet-, testnet- en devnetcontext duidelijk.",
          "Scheid persoonlijke, builder-, treasury- en testrollen.",
          "Een profiellabel voorkomt geen compromis van het apparaat.",
          "Controleer card/profiel vóór iedere ondertekening.",
        ],
        practiceEn: "Create a role map for mainnet personal, TESTNET training and builder testing accounts.",
        practiceNl: "Maak een rollenkaart voor persoonlijk mainnet, TESTNET-training en buildertests.",
      },
      {
        id: "signing",
        titleEn: "Signing XRPL transactions from websites",
        titleNl: "XRPL-transacties vanuit websites ondertekenen",
        summaryEn: "The convenience of browser signing increases the need to inspect every requested transaction and confirm the final hash.",
        summaryNl: "Het gemak van browserondertekening vergroot de noodzaak om ieder verzoek en de uiteindelijke hash te controleren.",
        pointsEn: [
          "Check domain, TLS, active account and network.",
          "Read the transaction type and all changed fields.",
          "Reject bulk or repeated requests you did not deliberately initiate.",
          "Confirm the response hash in an independent XRPL explorer.",
        ],
        pointsNl: [
          "Controleer domein, TLS, actief account en netwerk.",
          "Lees transactietype en alle gewijzigde velden.",
          "Weiger bulk- of herhaalde verzoeken die je niet bewust startte.",
          "Controleer de hash in een onafhankelijke XRPL-explorer.",
        ],
        practiceEn: "Use TESTNET to sign one Payment request and document the request, response and final validated hash.",
        practiceNl: "Onderteken op TESTNET één Payment-verzoek en documenteer request, response en gevalideerde hash.",
      },
      {
        id: "recovery",
        titleEn: "Backup and compromised-browser response",
        titleNl: "Back-up en reactie op browsercompromis",
        summaryEn: "Recovery planning must cover password loss, browser-profile loss, device compromise and potential exposure of imported key material.",
        summaryNl: "Herstelplanning moet wachtwoordverlies, browserprofielverlies, apparaatcompromis en mogelijke sleutelblootstelling afdekken.",
        pointsEn: [
          "Know how the account secret was generated and backed up.",
          "Do not rely only on a browser profile or extension installation.",
          "If compromise is suspected, move assets using a clean environment and new keys.",
          "Review regular-key or multisign options for higher-value operational accounts.",
        ],
        pointsNl: [
          "Weet hoe het accountgeheim is gegenereerd en geback-upt.",
          "Vertrouw niet alleen op browserprofiel of extensie-installatie.",
          "Verplaats bij vermoedelijk compromis via een schone omgeving naar nieuwe sleutels.",
          "Overweeg regular keys of multisign voor waardevollere operationele accounts.",
        ],
        practiceEn: "Write an incident sequence for a malicious extension discovered on the same browser profile.",
        practiceNl: "Schrijf een incidentvolgorde voor ontdekking van een kwaadaardige extensie in hetzelfde browserprofiel.",
      },
      {
        id: "decision",
        titleEn: "When Crossmark is or is not the right choice",
        titleNl: "Wanneer Crossmark wel of niet passend is",
        summaryEn: "Crossmark is useful for XRPL desktop dApps and development. Long-term storage or treasury signing may benefit from stronger hardware or multisign separation.",
        summaryNl: "Crossmark is nuttig voor XRPL-desktopdApps en ontwikkeling. Langetermijnopslag of treasury signing kan sterkere hardware- of multisignscheiding vereisen.",
        pointsEn: [
          "Good fit: desktop dApp user, developer, testnet operator or multi-profile user.",
          "Consider alternatives for offline key isolation.",
          "Keep browser-wallet balances proportional to their operational purpose.",
          "Use dedicated profiles and independent verification as standard procedure.",
        ],
        pointsNl: [
          "Goede match: desktop-dAppgebruiker, developer, testnetoperator of multiprofielgebruiker.",
          "Overweeg alternatieven voor offline sleutelisolatie.",
          "Houd browserwalletbalansen in verhouding tot hun operationele doel.",
          "Gebruik aparte profielen en onafhankelijke verificatie als standaard.",
        ],
        practiceEn: "Define a maximum balance and permission scope for a browser wallet used with experimental dApps.",
        practiceNl: "Bepaal een maximale balans en permissiescope voor een browserwallet bij experimentele dApps.",
      },
    ],
  },
  {
    id: "gemwallet",
    name: "GemWallet",
    categoryEn: "Decentralized XRPL browser extension",
    categoryNl: "Gedecentraliseerde XRPL-browserextensie",
    platforms: "Chrome-compatible browser extension",
    bestForEn: "XRPL web applications and users who prefer a lightweight browser-native wallet.",
    bestForNl: "XRPL-webapplicaties en gebruikers die een lichte browser-native wallet verkiezen.",
    notIdealForEn: "Users who want hardware-isolated signing or do not want private-key operations in a browser environment.",
    notIdealForNl: "Gebruikers die hardwaregeïsoleerd willen tekenen of geen sleutelhandelingen in een browseromgeving willen.",
    sourceLabel: "GemWallet official site",
    sourceUrl: "https://gemwallet.app/",
    verifiedOn: VERIFIED_ON,
    strengthsEn: [
      "XRPL-focused decentralized browser extension.",
      "Provider states that it uses no backend servers or account-data storage.",
      "Non-custodial dApp interaction and developer APIs.",
      "Simple direct transaction workflow for supported web applications.",
    ],
    strengthsNl: [
      "XRPL-gerichte gedecentraliseerde browserextensie.",
      "Volgens de aanbieder geen backendservers of opslag van accountdata.",
      "Non-custodial dApp-interactie en developer-API’s.",
      "Eenvoudige directe transactieworkflow voor ondersteunde webapps.",
    ],
    limitationsEn: [
      "Browser and device compromise remain relevant risks.",
      "A no-backend design does not make every connected dApp safe.",
      "Recovery depends on the user's own protected backup.",
      "Current network and feature support must be checked in the official user guide.",
    ],
    limitationsNl: [
      "Browser- en apparaatcompromis blijven relevante risico’s.",
      "Een ontwerp zonder backend maakt niet iedere gekoppelde dApp veilig.",
      "Herstel hangt af van de eigen beschermde back-up van de gebruiker.",
      "Controleer actuele netwerk- en featureondersteuning in de officiële handleiding.",
    ],
    sections: [
      {
        id: "model",
        titleEn: "Local extension storage and direct XRPL use",
        titleNl: "Lokale extensieopslag en direct XRPL-gebruik",
        summaryEn: "GemWallet states that wallet data is encrypted on the user's device and that the service does not operate a backend that stores account data.",
        summaryNl: "GemWallet vermeldt dat walletdata versleuteld op het gebruikersapparaat staat en dat geen backend accountdata opslaat.",
        pointsEn: [
          "Non-custodial means the user controls the account keys.",
          "Local storage shifts responsibility to device and password security.",
          "A dApp can request actions but should never receive the private key.",
          "Public XRPL account data remains visible independently of the wallet.",
        ],
        pointsNl: [
          "Non-custodial betekent dat de gebruiker de accountsleutels beheert.",
          "Lokale opslag verschuift verantwoordelijkheid naar apparaat- en wachtwoordbeveiliging.",
          "Een dApp kan acties aanvragen maar mag nooit de privésleutel ontvangen.",
          "Openbare XRPL-accountdata blijft onafhankelijk zichtbaar.",
        ],
        practiceEn: "Explain why no provider backend reduces one data exposure path but does not remove malware or phishing risk.",
        practiceNl: "Leg uit waarom geen providerbackend één blootstellingsroute vermindert maar malware- of phishingrisico niet verwijdert.",
      },
      {
        id: "setup",
        titleEn: "Official installation and browser isolation",
        titleNl: "Officiële installatie en browserisolatie",
        summaryEn: "Use the official download link, verify the extension identity and isolate wallet use from general browsing as much as practical.",
        summaryNl: "Gebruik de officiële downloadlink, controleer de extensie-identiteit en isoleer walletgebruik zo veel mogelijk van algemeen browsen.",
        pointsEn: [
          "Install from the official GemWallet website or linked store listing.",
          "Use a unique wallet password and dedicated browser profile.",
          "Back up account recovery material before funding.",
          "Disable unnecessary extensions and review browser synchronization.",
        ],
        pointsNl: [
          "Installeer via de officiële GemWallet-site of gekoppelde storevermelding.",
          "Gebruik een uniek walletwachtwoord en apart browserprofiel.",
          "Maak een back-up van herstelgegevens vóór financiering.",
          "Schakel onnodige extensies uit en controleer browsersynchronisatie.",
        ],
        practiceEn: "Verify the official extension listing and record the publisher information without storing wallet secrets.",
        practiceNl: "Controleer de officiële extensievermelding en noteer uitgeversinformatie zonder walletgeheimen op te slaan.",
      },
      {
        id: "dapps",
        titleEn: "Connecting to XRPL web applications",
        titleNl: "Verbinden met XRPL-webapplicaties",
        summaryEn: "GemWallet APIs allow websites to request account information and transaction signing. The user must evaluate both the domain and transaction content.",
        summaryNl: "GemWallet-API’s laten websites accountinformatie en transactiesigning aanvragen. De gebruiker moet domein én transactie-inhoud beoordelen.",
        pointsEn: [
          "Connect only after verifying the official domain.",
          "Treat every requested transaction as a separate decision.",
          "Disconnect sessions that are no longer needed.",
          "Verify transaction hashes outside the requesting website.",
        ],
        pointsNl: [
          "Verbind pas na controle van het officiële domein.",
          "Behandel iedere aangevraagde transactie als een apart besluit.",
          "Verbreek sessies die niet meer nodig zijn.",
          "Controleer transactiehashes buiten de aanvragende website.",
        ],
        practiceEn: "Connect to a TESTNET application, identify the requested account access and disconnect before signing.",
        practiceNl: "Verbind met een TESTNET-app, identificeer de gevraagde accounttoegang en verbreek vóór ondertekening.",
      },
      {
        id: "signing",
        titleEn: "Transaction review in an extension popup",
        titleNl: "Transactiecontrole in een extensievenster",
        summaryEn: "Small popup interfaces can hide context. Slow down, expand details where possible and match the request to the action you initiated.",
        summaryNl: "Kleine extensievensters kunnen context verbergen. Vertraag, open details en koppel het verzoek aan de actie die je zelf startte.",
        pointsEn: [
          "Check transaction type, account, destination, amount, currency and issuer.",
          "Watch for unexpected TrustSet, AccountSet, SignerListSet or NFT offer actions.",
          "Reject requests triggered by copied links or unsolicited messages.",
          "Keep an explorer open for post-signature verification.",
        ],
        pointsNl: [
          "Controleer transactietype, account, bestemming, bedrag, currency en issuer.",
          "Let op onverwachte TrustSet-, AccountSet-, SignerListSet- of NFT-offeracties.",
          "Weiger verzoeken uit gekopieerde links of ongevraagde berichten.",
          "Houd een explorer open voor verificatie na ondertekening.",
        ],
        practiceEn: "Review sample XRPL JSON for Payment, TrustSet and NFTokenAcceptOffer and identify their highest-risk fields.",
        practiceNl: "Bekijk voorbeeld-JSON voor Payment, TrustSet en NFTokenAcceptOffer en benoem de risicovolste velden.",
      },
      {
        id: "recovery",
        titleEn: "Backup, password loss and device compromise",
        titleNl: "Back-up, wachtwoordverlies en apparaatcompromis",
        summaryEn: "A local extension requires an independent recovery backup. Browser removal or device failure must not be the first time the recovery method is tested.",
        summaryNl: "Een lokale extensie vereist een onafhankelijke herstelback-up. Browserverwijdering of apparaatfalen mag niet het eerste hersteltestmoment zijn.",
        pointsEn: [
          "Keep recovery material offline and physically protected.",
          "Know the difference between extension password and account secret.",
          "Test recovery with an empty or low-value account.",
          "Move funds to fresh keys if the device may be compromised.",
        ],
        pointsNl: [
          "Bewaar herstelgegevens offline en fysiek beschermd.",
          "Ken het verschil tussen extensiewachtwoord en accountgeheim.",
          "Test herstel met een leeg account of lage waarde.",
          "Verplaats vermogen naar nieuwe sleutels bij mogelijk apparaatcompromis.",
        ],
        practiceEn: "Write a recovery plan for accidental extension removal and a separate incident plan for malware.",
        practiceNl: "Schrijf een herstelplan voor onbedoelde extensieverwijdering en een apart incidentplan voor malware.",
      },
      {
        id: "decision",
        titleEn: "When GemWallet is or is not the right choice",
        titleNl: "Wanneer GemWallet wel of niet passend is",
        summaryEn: "GemWallet can be suitable for direct browser-based XRPL use, but high-value storage should be evaluated separately from convenient dApp interaction.",
        summaryNl: "GemWallet kan geschikt zijn voor direct browsergebaseerd XRPL-gebruik, maar opslag van hoge waarde moet apart worden beoordeeld van dApp-gemak.",
        pointsEn: [
          "Good fit: lightweight XRPL web-app interaction and developer testing.",
          "Consider hardware or multisign separation for treasury balances.",
          "Use a balance and permission scope appropriate to browser risk.",
          "Verify current features in the official guide before committing to a workflow.",
        ],
        pointsNl: [
          "Goede match: lichte XRPL-webappinteractie en developertests.",
          "Overweeg hardware- of multisignscheiding voor treasurybalansen.",
          "Gebruik een balans en permissiescope passend bij browserrisico.",
          "Controleer actuele functies in de officiële handleiding vóór ingebruikname.",
        ],
        practiceEn: "Define which account roles are acceptable in a browser extension and which must remain on separate keys.",
        practiceNl: "Bepaal welke accountrollen in een browserextensie mogen en welke op aparte sleutels moeten blijven.",
      },
    ],
  },
  {
    id: "bifrost",
    name: "Bifrost Wallet",
    categoryEn: "Mobile multi-chain self-custody wallet",
    categoryNl: "Mobiele multichain self-custodywallet",
    platforms: "iOS · Android",
    bestForEn: "Users managing XRP alongside Flare, EVM assets, NFTs and mobile dApps.",
    bestForNl: "Gebruikers die XRP naast Flare, EVM-assets, NFT’s en mobiele dApps beheren.",
    notIdealForEn: "Users who need an XRPL-first interface with every native XRPL account-management feature.",
    notIdealForNl: "Gebruikers die een XRPL-first interface met iedere native accountfunctie nodig hebben.",
    sourceLabel: "Bifrost Wallet official site",
    sourceUrl: "https://bifrostwallet.com/",
    verifiedOn: VERIFIED_ON,
    strengthsEn: [
      "Mobile self-custody wallet with multiple supported blockchains.",
      "Integrated dApp browser and NFT gallery.",
      "Can manage XRP alongside assets from other ecosystems.",
      "Useful for users active across XRP Ledger and Flare-related environments.",
    ],
    strengthsNl: [
      "Mobiele self-custodywallet met meerdere blockchains.",
      "Geïntegreerde dApp-browser en NFT-galerij.",
      "Beheert XRP naast assets uit andere ecosystemen.",
      "Nuttig voor gebruikers actief op XRPL en Flare-gerelateerde omgevingen.",
    ],
    limitationsEn: [
      "Multi-chain interfaces increase network-selection and wrapped-asset confusion risk.",
      "A dApp browser introduces website, smart-contract and approval risks beyond XRPL.",
      "XRPL-specific functionality may not be as deep as an XRPL-first wallet.",
      "Users must distinguish native XRP Ledger XRP from similarly named assets on other networks.",
    ],
    limitationsNl: [
      "Multichaininterfaces vergroten risico op verkeerd netwerk en wrapped-assetverwarring.",
      "Een dApp-browser voegt website-, smartcontract- en approvalrisico’s toe buiten XRPL.",
      "XRPL-specifieke functionaliteit kan minder diep zijn dan bij een XRPL-first wallet.",
      "Gebruikers moeten native XRP Ledger XRP onderscheiden van gelijknamige assets op andere netwerken.",
    ],
    sections: [
      {
        id: "model",
        titleEn: "One wallet interface across multiple chains",
        titleNl: "Eén walletinterface voor meerdere chains",
        summaryEn: "Bifrost manages keys and accounts for multiple blockchain environments. The selected chain determines address format, fees, transaction rules and application risk.",
        summaryNl: "Bifrost beheert sleutels en accounts voor meerdere blockchainomgevingen. De gekozen chain bepaalt adresformaat, kosten, transactieregels en applicatierisico.",
        pointsEn: [
          "The same app can display assets governed by very different protocols.",
          "Always identify the network before copying an address or sending an asset.",
          "XRP on XRPL is not automatically interchangeable with representations on other networks.",
          "Self-custody responsibility applies across every account derived from the backup.",
        ],
        pointsNl: [
          "Dezelfde app toont assets onder zeer verschillende protocollen.",
          "Identificeer altijd het netwerk vóór adreskopie of verzending.",
          "XRP op XRPL is niet automatisch uitwisselbaar met representaties op andere netwerken.",
          "Self-custodyverantwoordelijkheid geldt voor ieder account uit de back-up.",
        ],
        practiceEn: "Compare an XRPL XRP receive screen with an EVM receive screen and identify the network-specific differences.",
        practiceNl: "Vergelijk een XRPL-XRP-ontvangstscherm met een EVM-ontvangstscherm en benoem de netwerkverschillen.",
      },
      {
        id: "setup",
        titleEn: "Mobile setup and backup scope",
        titleNl: "Mobiele setup en reikwijdte van de back-up",
        summaryEn: "A multichain backup can control many derived accounts. Treat it as a master recovery authority and understand which chains and accounts it restores.",
        summaryNl: "Een multichainback-up kan veel afgeleide accounts beheren. Behandel die als masterherstelbevoegdheid en begrijp welke chains en accounts worden hersteld.",
        pointsEn: [
          "Install from the official app-store links.",
          "Record recovery material offline and enable device security.",
          "Test recovery using a controlled low-value setup.",
          "Document which accounts and networks belong to the same backup.",
        ],
        pointsNl: [
          "Installeer via officiële app-storelinks.",
          "Leg herstelgegevens offline vast en activeer toestelbeveiliging.",
          "Test herstel met een gecontroleerde lage-waardesetup.",
          "Documenteer welke accounts en netwerken onder dezelfde back-up vallen.",
        ],
        practiceEn: "Build an account map showing each supported network you actually use and the recovery dependency behind it.",
        practiceNl: "Maak een accountkaart van ieder gebruikt netwerk en de achterliggende herstelafhankelijkheid.",
      },
      {
        id: "xrpl",
        titleEn: "Using native XRP safely",
        titleNl: "Native XRP veilig gebruiken",
        summaryEn: "Before receiving or sending XRP, verify that the active network is XRP Ledger and that the destination expects a native XRPL account and any required destination tag.",
        summaryNl: "Controleer vóór ontvangst of verzending dat XRP Ledger actief is en dat de bestemming een native XRPL-account en eventuele destination tag verwacht.",
        pointsEn: [
          "Confirm network label and r-address format.",
          "Check exchange destination-tag requirements.",
          "Use a small test when moving between multi-chain services.",
          "Verify final XRPL delivery with a transaction hash and delivered amount.",
        ],
        pointsNl: [
          "Controleer netwerklabel en r-adresformaat.",
          "Controleer destination-tagvereisten van exchanges.",
          "Gebruik een kleine test bij overdracht tussen multichaindiensten.",
          "Verifieer XRPL-levering met transactiehash en geleverd bedrag.",
        ],
        practiceEn: "Create a pre-send checklist for XRP from Bifrost to an exchange account requiring a destination tag.",
        practiceNl: "Maak een verzendchecklist voor XRP vanuit Bifrost naar een exchangeaccount met destination tag.",
      },
      {
        id: "dapps",
        titleEn: "dApp browser, approvals and smart-contract risk",
        titleNl: "dApp-browser, approvals en smartcontractrisico",
        summaryEn: "Bifrost's dApp browser can access applications on several smart-contract networks. Those approval models differ from XRPL transaction signing.",
        summaryNl: "De Bifrost-dApp-browser kan applicaties op meerdere smartcontractnetwerken openen. Die approvalmodellen verschillen van XRPL-transactiesigning.",
        pointsEn: [
          "Verify the active network and contract address.",
          "Understand token approvals and spending allowances before confirmation.",
          "Do not generalize XRPL finality or trustline concepts to EVM approvals.",
          "Disconnect and revoke permissions that are no longer required.",
        ],
        pointsNl: [
          "Controleer actief netwerk en contractadres.",
          "Begrijp token approvals en spending allowances vóór bevestiging.",
          "Pas XRPL-finaliteit of trustlineconcepten niet automatisch toe op EVM-approvals.",
          "Verbreek en trek niet meer benodigde permissies in.",
        ],
        practiceEn: "Compare an XRPL Payment with an EVM token approval and list why they require different risk checks.",
        practiceNl: "Vergelijk een XRPL Payment met een EVM-tokenapproval en benoem waarom de risicocontroles verschillen.",
      },
      {
        id: "recovery",
        titleEn: "Multichain incident and recovery planning",
        titleNl: "Multichainincident- en herstelplanning",
        summaryEn: "One exposed backup can affect multiple chains. Incident response must identify every derived account, token approval and connected application.",
        summaryNl: "Eén blootgestelde back-up kan meerdere chains raken. Incidentrespons moet ieder afgeleid account, tokenapproval en gekoppelde applicatie identificeren.",
        pointsEn: [
          "Assume all accounts under an exposed seed may be affected.",
          "Prioritize moving assets and revoking approvals by risk and liquidity.",
          "Use clean devices and new recovery material for migration.",
          "Keep an inventory before an incident occurs.",
        ],
        pointsNl: [
          "Ga ervan uit dat alle accounts onder een blootgestelde seed geraakt kunnen zijn.",
          "Prioriteer assetmigratie en intrekken van approvals op risico en liquiditeit.",
          "Gebruik schone apparaten en nieuw herstelmateriaal voor migratie.",
          "Houd vóór een incident een inventaris bij.",
        ],
        practiceEn: "Create a multichain incident worksheet listing account, network, asset, approval and migration destination.",
        practiceNl: "Maak een multichainincidentwerkblad met account, netwerk, asset, approval en migratiebestemming.",
      },
      {
        id: "decision",
        titleEn: "When Bifrost is or is not the right choice",
        titleNl: "Wanneer Bifrost wel of niet passend is",
        summaryEn: "Bifrost is useful when a user genuinely needs several ecosystems in one mobile wallet. Simplicity can be safer when only XRPL is required.",
        summaryNl: "Bifrost is nuttig wanneer meerdere ecosystemen echt in één mobiele wallet nodig zijn. Eenvoud kan veiliger zijn wanneer alleen XRPL nodig is.",
        pointsEn: [
          "Good fit: active Flare/EVM and XRP user needing one mobile interface.",
          "Consider an XRPL-first wallet for deeper native workflows.",
          "Consider hardware separation for long-term or treasury balances.",
          "More networks mean more operational rules to learn and maintain.",
        ],
        pointsNl: [
          "Goede match: actieve Flare/EVM- en XRP-gebruiker met één mobiele interface.",
          "Overweeg een XRPL-first wallet voor diepere native flows.",
          "Overweeg hardwarescheiding voor langetermijn- of treasurybalansen.",
          "Meer netwerken betekenen meer operationele regels om te leren en onderhouden.",
        ],
        practiceEn: "Decide whether your real use case needs a multichain wallet or whether two specialized wallets reduce risk and confusion.",
        practiceNl: "Bepaal of je echte use case een multichainwallet nodig heeft of dat twee gespecialiseerde wallets risico en verwarring verminderen.",
      },
    ],
  },
];
