export type DefiDirectoryCategory = "yield" | "dex" | "analytics" | "nft" | "xahau";

export type DefiDirectoryEntry = {
  id: string;
  name: string;
  category: DefiDirectoryCategory;
  verifiedDomain: boolean;
  url: string;
  sourceLabel: string;
  summaryEn: string;
  summaryNl: string;
  technologyEn: string;
  technologyNl: string;
  possibleBenefitEn: string;
  possibleBenefitNl: string;
  risksEn: string[];
  risksNl: string[];
  custodyEn: string;
  custodyNl: string;
  walletEn: string;
  walletNl: string;
};

export const DEFI_DIRECTORY: DefiDirectoryEntry[] = [
  {
    id: "soil",
    name: "SOIL",
    category: "yield",
    verifiedDomain: true,
    url: "https://soil.co/",
    sourceLabel: "Official SOIL website",
    summaryEn: "Vault products that connect digital assets with institutional credit and treasury strategies, including XRPL-focused products.",
    summaryNl: "Vaultproducten die digitale assets verbinden met institutioneel krediet en treasurystrategieën, waaronder XRPL-gerichte producten.",
    technologyEn: "XRPL vault interfaces and off-ledger legal or investment structures that generate the stated return.",
    technologyNl: "XRPL-vaultinterfaces en off-ledger juridische of investeringsstructuren die het genoemde rendement genereren.",
    possibleBenefitEn: "Potential fixed or structured yield while remaining denominated in XRP or RLUSD, depending on the product.",
    possibleBenefitNl: "Mogelijk vast of gestructureerd rendement terwijl de positie in XRP of RLUSD blijft, afhankelijk van het product.",
    risksEn: ["Counterparty and credit risk", "Lock-up or notice periods", "Legal terms and jurisdiction", "Custody and product eligibility"],
    risksNl: ["Tegenpartij- en kredietrisico", "Lock-up- of opzegtermijnen", "Juridische voorwaarden en jurisdictie", "Custody en producttoegang"],
    custodyEn: "Product-specific; review who receives, holds and deploys the assets.",
    custodyNl: "Productafhankelijk; controleer wie de assets ontvangt, bewaart en inzet.",
    walletEn: "XRPL-compatible wallet where supported; KYC or an account may also be required.",
    walletNl: "XRPL-compatibele wallet waar ondersteund; KYC of een account kan ook vereist zijn.",
  },
  {
    id: "doppler",
    name: "Doppler Finance",
    category: "yield",
    verifiedDomain: true,
    url: "https://docs.doppler.finance/introduction",
    sourceLabel: "Official Doppler documentation",
    summaryEn: "An XRPfi project describing yield products and broader DeFi services for XRP and XRPL ecosystem assets.",
    summaryNl: "Een XRPfi-project dat yieldproducten en bredere DeFi-diensten voor XRP en XRPL-assets beschrijft.",
    technologyEn: "Product-dependent vault, lending and cross-network infrastructure rather than a single native XRPL primitive.",
    technologyNl: "Productafhankelijke vault-, lending- en cross-networkinfrastructuur in plaats van één native XRPL-primitive.",
    possibleBenefitEn: "Potential yield or capital-use products for assets that would otherwise remain idle.",
    possibleBenefitNl: "Mogelijke yield- of kapitaalproducten voor assets die anders ongebruikt blijven.",
    risksEn: ["Counterparty and custody risk", "Variable yield", "Protocol and integration risk", "Product terms can change"],
    risksNl: ["Tegenpartij- en custodyrisico", "Variabel rendement", "Protocol- en integratierisico", "Productvoorwaarden kunnen veranderen"],
    custodyEn: "Review each product separately; marketing language does not determine actual custody.",
    custodyNl: "Controleer elk product apart; marketingtaal bepaalt niet de werkelijke custody.",
    walletEn: "Depends on the selected network, product and supported wallet flow.",
    walletNl: "Hangt af van het gekozen netwerk, product en ondersteunde walletflow.",
  },
  {
    id: "anodos",
    name: "Anodos / ANODEX",
    category: "dex",
    verifiedDomain: true,
    url: "https://apps.anodos.finance/",
    sourceLabel: "Official Anodos applications",
    summaryEn: "Interfaces for XRPL DEX trading, liquidity and account management, including ANODEX and a Xaman xApp.",
    summaryNl: "Interfaces voor XRPL DEX-handel, liquiditeit en accountbeheer, waaronder ANODEX en een Xaman-xApp.",
    technologyEn: "Uses XRPL native order books, issued currencies and liquidity functionality through a non-custodial interface.",
    technologyNl: "Gebruikt native XRPL-orderboeken, issued currencies en liquiditeitsfuncties via een non-custodial interface.",
    possibleBenefitEn: "Direct access to XRPL trading and liquidity tools without transferring ownership to a central exchange.",
    possibleBenefitNl: "Directe toegang tot XRPL-handel en liquiditeit zonder eigendom aan een centrale exchange over te dragen.",
    risksEn: ["Token and issuer risk", "Slippage and thin liquidity", "Wrong trustline or asset", "Transaction-signing mistakes"],
    risksNl: ["Token- en issuerrisico", "Slippage en lage liquiditeit", "Verkeerde trustline of asset", "Fouten bij ondertekening"],
    custodyEn: "Presented as an on-chain interface; the wallet signs transactions.",
    custodyNl: "Gepresenteerd als on-chain interface; de wallet ondertekent transacties.",
    walletEn: "Compatible XRPL wallet; exact support depends on the selected Anodos application.",
    walletNl: "Compatibele XRPL-wallet; exacte ondersteuning hangt af van de gekozen Anodos-applicatie.",
  },
  {
    id: "xpmarket",
    name: "XPMarket",
    category: "dex",
    verifiedDomain: true,
    url: "https://xpmarket.com/",
    sourceLabel: "Official XPMarket website",
    summaryEn: "XRPL token discovery, DEX and AMM trading, NFT markets, launch tooling and ecosystem analytics.",
    summaryNl: "XRPL-tokendekking, DEX- en AMM-handel, NFT-markten, launchtools en ecosysteemanalyse.",
    technologyEn: "Interfaces with XRPL native DEX, AMM, issued assets and XLS-20 NFT functionality.",
    technologyNl: "Werkt met native XRPL DEX, AMM, issued assets en XLS-20 NFT-functionaliteit.",
    possibleBenefitEn: "Research and on-ledger actions in one interface, with peer-to-peer settlement for supported functions.",
    possibleBenefitNl: "Onderzoek en on-ledger acties in één interface, met peer-to-peer afwikkeling voor ondersteunde functies.",
    risksEn: ["Market and token risk", "Liquidity and price-impact risk", "Unverified issuers", "Phishing clones"],
    risksNl: ["Markt- en tokenrisico", "Liquiditeits- en prijsimpactrisico", "Ongeverifieerde issuers", "Phishingkopieën"],
    custodyEn: "Non-custodial for described on-ledger trading; verify each connected service separately.",
    custodyNl: "Non-custodial voor beschreven on-ledger handel; controleer elke gekoppelde dienst apart.",
    walletEn: "Supported XRPL wallet; inspect every transaction request before signing.",
    walletNl: "Ondersteunde XRPL-wallet; controleer elk transactieverzoek vóór ondertekening.",
  },
  {
    id: "sologenic",
    name: "Sologenic",
    category: "dex",
    verifiedDomain: true,
    url: "https://sologenic.org/",
    sourceLabel: "Official Sologenic website",
    summaryEn: "A broader XRPL ecosystem with DEX, AMM, quick swap, NFT, bridge and token-management interfaces.",
    summaryNl: "Een breder XRPL-ecosysteem met DEX-, AMM-, quick-swap-, NFT-, bridge- en tokenbeheerinterfaces.",
    technologyEn: "Combines XRPL native trading and tokenization functions with additional bridge and application services.",
    technologyNl: "Combineert native XRPL-handel en tokenisatie met aanvullende bridge- en applicatiediensten.",
    possibleBenefitEn: "One interface for several XRPL market and tokenization activities.",
    possibleBenefitNl: "Eén interface voor meerdere XRPL-markt- en tokenisatieactiviteiten.",
    risksEn: ["Bridge and cross-chain risk", "Issuer and token risk", "Liquidity risk", "Service-specific terms"],
    risksNl: ["Bridge- en cross-chainrisico", "Issuer- en tokenrisico", "Liquiditeitsrisico", "Dienstspecifieke voorwaarden"],
    custodyEn: "XRPL DEX actions can be self-custodied; bridge and fiat services require separate review.",
    custodyNl: "XRPL DEX-acties kunnen self-custody zijn; bridge- en fiatdiensten vereisen aparte controle.",
    walletEn: "Supported XRPL wallet for native actions; other networks may require other wallets.",
    walletNl: "Ondersteunde XRPL-wallet voor native acties; andere netwerken kunnen andere wallets vereisen.",
  },
  {
    id: "onthedex",
    name: "OnTheDEX.live",
    category: "analytics",
    verifiedDomain: true,
    url: "https://onthedex.live/",
    sourceLabel: "Official OnTheDEX.live website",
    summaryEn: "XRPL token activity, prices, trading pairs, seller analysis, portfolio views and API data.",
    summaryNl: "XRPL-tokenactiviteit, prijzen, handelsparen, verkopersanalyse, portfolioweergaven en API-data.",
    technologyEn: "Indexes and presents public XRPL DEX data; analytics are an interpretation layer above raw ledger records.",
    technologyNl: "Indexeert en presenteert openbare XRPL DEX-data; analyses zijn een interpretatielaag boven ruwe ledgergegevens.",
    possibleBenefitEn: "Independent market observations and historical context before a user signs a transaction elsewhere.",
    possibleBenefitNl: "Onafhankelijke marktobservaties en historische context voordat een gebruiker elders ondertekent.",
    risksEn: ["Indexer completeness", "Metric methodology", "Delayed or sampled data", "Analytics do not predict outcomes"],
    risksNl: ["Volledigheid van indexer", "Methodologie van statistieken", "Vertraagde of gesamplede data", "Analyse voorspelt geen uitkomsten"],
    custodyEn: "Analytics use does not require custody; portfolio views may use public addresses.",
    custodyNl: "Analysegebruik vereist geen custody; portfolioweergaven kunnen openbare adressen gebruiken.",
    walletEn: "Not required for basic research; optional for supported portfolio or account features.",
    walletNl: "Niet nodig voor basisonderzoek; optioneel voor ondersteunde portfolio- of accountfuncties.",
  },
  {
    id: "xrpcafe",
    name: "XRP Café",
    category: "nft",
    verifiedDomain: true,
    url: "https://xrp.cafe/",
    sourceLabel: "XRP Café domain and XRPL developer profile",
    summaryEn: "An XRPL-native NFT marketplace and creator-tool ecosystem built around XLS-20 NFTs.",
    summaryNl: "Een XRPL-native NFT-marktplaats en creator-tool-ecosysteem rond XLS-20 NFT’s.",
    technologyEn: "Uses XRPL native NFT mint, offer and transfer functionality with external metadata storage and indexing.",
    technologyNl: "Gebruikt native XRPL NFT-mint-, offer- en transferfuncties met externe metadataopslag en indexering.",
    possibleBenefitEn: "Create, discover and trade native XRPL NFTs with marketplace tooling.",
    possibleBenefitNl: "Maak, ontdek en verhandel native XRPL-NFT’s met marktplaatstools.",
    risksEn: ["Collection authenticity", "Metadata permanence", "Thin markets", "Royalty and marketplace terms"],
    risksNl: ["Authenticiteit van collecties", "Bestendigheid van metadata", "Dunne markten", "Royalty- en marktplaatsvoorwaarden"],
    custodyEn: "Native NFT actions are signed by the user wallet; metadata and marketplace services remain external dependencies.",
    custodyNl: "Native NFT-acties worden door de gebruikerswallet ondertekend; metadata en marktplaatsdiensten blijven externe afhankelijkheden.",
    walletEn: "XRPL wallet with XLS-20 transaction support.",
    walletNl: "XRPL-wallet met ondersteuning voor XLS-20-transacties.",
  },
  {
    id: "xmagnetic-review",
    name: "xMagnetic",
    category: "dex",
    verifiedDomain: false,
    url: "",
    sourceLabel: "Domain verification pending",
    summaryEn: "A known XRPL DeFi name, but conflicting domains and claims require manual source verification before OTT links users out.",
    summaryNl: "Een bekende XRPL DeFi-naam, maar conflicterende domeinen en claims vereisen handmatige broncontrole voordat OTT gebruikers doorstuurt.",
    technologyEn: "Reported DEX, AMM, farming, NFT and token functionality; each claim must be matched to a verified official source.",
    technologyNl: "Gerapporteerde DEX-, AMM-, farming-, NFT- en tokenfuncties; elke claim moet aan een geverifieerde officiële bron worden gekoppeld.",
    possibleBenefitEn: "Potentially broad XRPL market tooling after official-source verification.",
    possibleBenefitNl: "Mogelijk brede XRPL-markttools na verificatie van de officiële bron.",
    risksEn: ["Conflicting domains", "Phishing and clone risk", "Unverified product claims", "Wallet-signing risk"],
    risksNl: ["Conflicterende domeinen", "Phishing- en kopierisico", "Ongeverifieerde productclaims", "Wallet-ondertekeningsrisico"],
    custodyEn: "Not assessed until the official product source is verified.",
    custodyNl: "Niet beoordeeld totdat de officiële productbron is geverifieerd.",
    walletEn: "Do not connect through an unverified domain.",
    walletNl: "Koppel geen wallet via een niet-geverifieerd domein.",
  },
  {
    id: "onexah-review",
    name: "OneXAH",
    category: "xahau",
    verifiedDomain: false,
    url: "",
    sourceLabel: "Official product documentation pending",
    summaryEn: "A developing Xahau DeFi concept associated with Hooks-based on-ledger logic; OTT will not link out until official documentation is confirmed.",
    summaryNl: "Een ontwikkelend Xahau DeFi-concept rond Hooks-gebaseerde on-ledger logica; OTT linkt pas door na bevestigde officiële documentatie.",
    technologyEn: "Reported use of Xahau Hooks and liquidity mechanisms; production state and controls require verification.",
    technologyNl: "Gerapporteerd gebruik van Xahau Hooks en liquiditeitsmechanismen; productiestatus en controles vereisen verificatie.",
    possibleBenefitEn: "Potential programmable DeFi workflows on Xahau after technical and source review.",
    possibleBenefitNl: "Mogelijke programmeerbare DeFi-workflows op Xahau na technische en broncontrole.",
    risksEn: ["Early-stage product risk", "Hooks and code risk", "Liquidity risk", "Incomplete documentation"],
    risksNl: ["Risico van vroeg productstadium", "Hooks- en coderisico", "Liquiditeitsrisico", "Onvolledige documentatie"],
    custodyEn: "Not assessed until official product and transaction documentation is available.",
    custodyNl: "Niet beoordeeld totdat officiële product- en transactiedocumentatie beschikbaar is.",
    walletEn: "Do not sign until network, Hook and destination details are independently verified.",
    walletNl: "Onderteken niets totdat netwerk-, Hook- en bestemmingsdetails onafhankelijk zijn gecontroleerd.",
  },
];
