// 🛰️ OTT TERMINAL MAINNET PROTOCOL CONFIGURATION
export const OTT_PROTOCOL_CONFIG = {
  // 🪙 TOKEN FACTORY CONFIGURATION
  OFFICIAL_TOKEN_ISSUER: "rLATER_JE_ECHTE_ISSUER_ADRES_HIER_PLAKKEN", 
  TOKEN_CURRENCY_CODE: "OTT",
  TOTAL_MAX_SUPPLY: "589000000", // Gekoppeld aan de 589 missie

  // 🖼️ XLS-20 NFT FORGE CONFIGURATION
  DEFAULT_NFT_TAXON: 0,
  ROYALTY_FEE_PERCENTAGE: 500, // 5% Royalties voor het OTT ecosysteem

  // 🛠️ APPLICATIE STATUS
  TERMINAL_VERSION: "v0.9.238-Production-Shell",
  NETWORK_TARGET: "XRPL Mainnet / Xahau Protocol"
};